default_platform(:ios)

platform :ios do

  desc "Build the app"
  lane :build do
    build_ios_app(
      workspace: "Example.xcworkspace",
      scheme: "Example",
      export_method: 'ad-hoc',
      skip_package_ipa: true,
      export_xcargs: "-allowProvisioningUpdates -exportProvisioningProfile 'AD_HOC_PROFILE_NAME' -exportSigningIdentity 'iPhone Distribution'"
    )
  end  
end
