name: Build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: macos-latest
    environment:
      name: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Tuist
      run: curl -Ls https://install.tuist.io | bash
      working-directory: Example/

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Set up fastlane
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
      working-directory: Example/

    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: bundle exec danger
      working-directory: Example/

    - name: Tuist fetch
      run: tuist fetch
      working-directory: Example/

    - name: Tuist generate
      run: tuist generate
      working-directory: Example/

    - name: Build the app
      run: bundle exec fastlane build
      working-directory: Example/